#!/bin/sh

if [ $# -lt 2 ]; then
  echo "Usage: compile <source-file> <target-file>" >&2
  exit 1
fi

compiler="$(dirname "$0")/brainfuck"

source_filename=$1
object_filename=$(mktemp --dry-run -q --suffix '.o')
target_filename=$2

$compiler "$source_filename" "$object_filename"
clang "$object_filename" -o "$target_filename"
rm -f "$object_filename"
